# .Synopsis
#     Bicep deployment pipeline
#
# .NOTES
#     Author     : Roman Rabodzei
#     Version    : 1.0.240616
#
#             _
#         .__(.)<  (MEOW)
#          \___)
#  ~~~~~~~~~~~~~~~~~~~~~~~~

name: Bicep Deployment pipeline

trigger: none

pr: none

parameters:
  - name: deploymentLocation
    displayName: "Deployment location"
    type: string
    default: "west europe"
  - name: deploymentEnvironment
    displayName: "Deployment environment"
    type: string
    default: "poc"

variables:
  deploymentName: "ado_pipeline_1.0.$(Rev:.r)"


pool:
  vmImage: "ubuntu-latest"

stages:
  - stage: bicep_check_changes
    displayName: "Preview infrastructure changes"
    jobs:
      - job:
        steps:
          - checkout: self
          - task: AzureCLI@2
            displayName: "Preview changes"
            inputs:
              azureSubscription: $(subscription)
              scriptType: "bash"
              scriptLocation: "inlineScript"
              inlineScript: |
                az deployment sub what-if --name $(deploymentName) --location "${{ parameters.deploymentLocation }}" --template-file ./main.bicep --parameters deploymentEnvironment="${{ parameters.deploymentEnvironment }}"
              workingDirectory: "$(system.defaultWorkingDirectory)/bicep"

  - stage: bicep_deploy
    displayName: "Deploy infrastructure"
    dependsOn: bicep_check_changes
    jobs:
      - deployment:
        environment: ${{ parameters.deploymentEnvironment }}
        displayName: "Deploy infrastructure"
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self
                - task: AzureCLI@2
                  displayName: "Deploy infrastructure"
                  inputs:
                    azureSubscription: $(subscription)
                    scriptType: "bash"
                    scriptLocation: "inlineScript"
                    inlineScript: |
                      az deployment sub create --name $(deploymentName) --location "${{ parameters.deploymentLocation }}" --template-file ./main.bicep --parameters deploymentEnvironment="${{ parameters.deploymentEnvironment }}"
                    workingDirectory: "$(system.defaultWorkingDirectory)/bicep"
