# .Synopsis
#     Bicep linter pipeline
#
# .NOTES
#     Author     : Roman Rabodzei
#     Version    : 1.0.240617
#
#             _
#         .__(.)<  (MEOW)
#          \___)
#  ~~~~~~~~~~~~~~~~~~~~~~~~

name: Bicep Linter

on:
  push:
    branches:
      - 'main'
      - 'feature/*'
    # paths:
    #   - 'bicep/**'
  # pull_request:
  #   branches:
  #     - main
  #   paths:
  #     - ./bicep/*

permissions:
  contents: read

jobs:
  bicep_linter:
    name: Bicep Linter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Bicep Build
        run: |
          az bicep build --file ./bicep/main.bicep

      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Preflight Validation
        run: |
          az deployment sub validate --name $GITHUB_RUN_ID --location westeurope --template-file ./bicep/main.bicep --parameters deploymentEnvironment=linter
