# .Synopsis
#     Bicep linter pipeline
#
# .NOTES
#     Author     : Roman Rabodzei
#     Version    : 1.0.240616
#
#             _
#         .__(.)<  (MEOW)
#          \___)
#  ~~~~~~~~~~~~~~~~~~~~~~~~

name: Bicep Linter

on:
  pull_request:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  bicep_linter:
    name: Bicep Linter
    runs-on: ubuntu-latest
    environment: "linter"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Bicep Build
        run: |
          az bicep build --file ./bicep/main.bicep

      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Preflight Validation
        run: |
          az deployment sub validate --name $GITHUB_RUN_ID --location westeurope --template-file ./bicep/main.bicep --parameters deploymentEnvironment=linter
